---
kind: pipeline
type: kubernetes
name: staging

trigger:
  branch:
    - staging

steps:
  - name: publish-backend
    image: plugins/kaniko-ecr
    settings:
      create_repository: true
      registry: 795250896452.dkr.ecr.us-east-1.amazonaws.com
      repo: industrysolutions/retail-customer-retention-backend
      tags:
        - git-${DRONE_COMMIT_SHA:0:7}
        - latest
      dockerfile: Dockerfile
      access_key:
        from_secret: ecr_access_key
      secret_key:
        from_secret: ecr_secret_key
    when:
      event:
        - push

  - name: deploy-backend-staging
    image: public.ecr.aws/kanopy/drone-helm:v3
    settings:
      chart: mongodb/web-app
      chart_version: 4.30.0
      add_repos: [mongodb=https://10gen.github.io/helm-charts]
      namespace: industrysolutions
      release: retail-customer-retention-backend-staging
      values:
        - "image.tag=git-${DRONE_COMMIT_SHA:0:7}"
        - "image.repository=795250896452.dkr.ecr.us-east-1.amazonaws.com/industrysolutions/retail-customer-retention-backend"
        - "ingress.enabled=true"
        - "ingress.hosts[0]=retail-customer-retention-backend.industrysolutions.staging.corp.mongodb.com"
        - "mesh.enabled=true"
        - "resources.limits.cpu=1000m"
        - "resources.limits.memory=1024Mi"
        - "resources.requests.cpu=250m"
        - "resources.requests.memory=256Mi"
      api_server: https://api.staging.corp.mongodb.com
      kubernetes_token:
        from_secret: staging_kubernetes_token
      values_files: [ "environments/staging.yaml" ]
    when:
      event:
        - push
---
kind: pipeline
type: kubernetes
name: prod

trigger:
  branch:
    - main

steps:
  - name: publish-backend
    image: plugins/kaniko-ecr
    settings:
      create_repository: true
      registry: 795250896452.dkr.ecr.us-east-1.amazonaws.com
      repo: industrysolutions/retail-customer-retention-backend-prod
      tags:
        - git-${DRONE_COMMIT_SHA:0:7}
        - latest
      dockerfile: Dockerfile
      access_key:
        from_secret: ecr_access_key
      secret_key:
        from_secret: ecr_secret_key
    when:
      event:
        - push

  - name: deploy-backend-prod
    image: public.ecr.aws/kanopy/drone-helm:v3
    settings:
      chart: mongodb/web-app
      chart_version: 4.30.0
      add_repos: [mongodb=https://10gen.github.io/helm-charts]
      namespace: industrysolutions
      release: retail-customer-retention-backend-prod
      values:
        - "image.tag=git-${DRONE_COMMIT_SHA:0:7}"
        - "image.repository=795250896452.dkr.ecr.us-east-1.amazonaws.com/industrysolutions/retail-customer-retention-backend-prod"
        - "ingress.enabled=true"
        - "ingress.hosts[0]=retail-customer-retention-backend.industrysolutions.prod.corp.mongodb.com"
        - "mesh.enabled=true"
        - "resources.limits.cpu=1000m"
        - "resources.limits.memory=1024Mi"
        - "resources.requests.cpu=250m"
        - "resources.requests.memory=256Mi"
      api_server: https://api.prod.corp.mongodb.com
      kubernetes_token:
        from_secret: prod_kubernetes_token
      values_files: [ "environments/prod.yaml" ]
    when:
      event:
        - push
