env:
  NODE_ENV: staging

envSecrets:
  MONGODB_URI: retail-customer-retention-backend
  AWS_REGION: retail-customer-retention-backend
  AWS_ACCESS_KEY_ID: retail-customer-retention-backend
  AWS_SECRET_ACCESS_KEY: retail-customer-retention-backend
  VOYAGE_API_KEY: retail-customer-retention-backend

# Optional: Service account for AWS role integration
serviceAccount:
  enabled: true
  irsa:
    accountId: "275662791714"
    roleName: "kanopy-staging-cicd-irsa"
